### ISSUE TITLE
What is the difference between this and the Rust API bindings on the IPFS site?

### ISSUE THREAD

**Issue by icefoxen** [gkbrk/rust-ipfs-api#1]
https://github.com/ipfs/ipfs#api-client-libraries lists two Rust IPFS client libraries:

 * https://github.com/rschulman/rust-ipfs-api which hasn't really been updated in years
 * https://github.com/rmnoff/rust-ipfs-api which was updated a few months ago

But, neither of those actually have published crates, it seems.

So, basically, as a user... which should I use???

**Comment by leavehouse** [comment]
I feel I should also add a link to some HTTP API bindings I was working on:

https://github.com/leavehouse/rust-ipfs-api

I've set this aside for now, but you can see usage examples [here](https://github.com/leavehouse/rust-ipfs-api/blob/master/src/test_stuff.rs). It exposes a futures-based API (e.g. `ipfs.cat("<multihash>")` returns a future)

**Comment by icefoxen** [comment]
I like the idea of unifying efforts.

Perhaps to start with we want an crate that defines the IPFS API *types*, serializable and deserializeable with Serde, and then there can be multiple implementations using whatever they want to actually shuffle them to and from a server (reqwest with this crate, futures with your crate, etc)?

**Comment by ferristseng** [comment]
I am also working on this, and have most of the API types implemented (I believe I have all of the response types fleshed out). I'm still trying to figure out how some of the IPFS API works because it doesn't seem consistent with the documentation.

Like @leavehouse, my implementation is also exposing a futures-based API, but I was thinking about implementing a separate client type that hides the asynchronous stuff from the user.

https://github.com/ferristseng/rust-ipfs-api

I have a bunch of examples, so you can get kind of a feel for how it works...but the documentation is pretty lacking at the moment. I can also work on separating out the types into separate crates if that would help you out.

**Comment by matthiasbeyer** [comment]
OPs please continue your work on this crate. I'd love to be able to implement my application idea in Rust with IPFS bindings rather than in Go... **please** continue your work!

**Comment by gkbrk** [comment]
@matthiasbeyer Is there any API in particular that will be useful to you? Just getting an idea of what should be focused on first.

**Comment by matthiasbeyer** [comment]
Well, I am still in the "thinking about my idea"-phase of the project, so there is no code and nothing but thoughts and [a blog article about my idea](https://beyermatthias.de/blog/2017/10/31/blueprint-of-a-distributed-social-network-on-ipfs---and-its-problems/),... So I really don't know which APIs I would need. I don't even know what APIs exist... I only know what _technologies_ exist and how I could use them to get to my idea,... but not _how_ to use them.

From the top of my head:

* IPFS
    * Read/Write from/to IPFS - thinking of JSON for structured data and binary blobs (text, audio, video) for content
    * pubsub
* IPLD
    * for data traversal in IPFS
* IPNS 
    * name publishing (with different keys)
    * name resolution
    * Key management / creation / etc

**Comment by ferristseng** [comment]
@matthiasbeyer Not to hijack the thread, but I have most of that stuff implemented in the library I mentioned above (expect for IPLD, I haven't heard of that before). The documentation is pretty sparse at the moment, but there are a ton of examples that should cover most of the use cases you mentioned.

**Comment by icefoxen** [comment]
@ferristseng It looks nice, but could it be possible to actually release the crate on crates.io ?  And maybe make a more distinguishable name...
